### ISSUE TITLE
🚀 Possible Roadmap 

### ISSUE THREAD

**Issue by SamuelGuillemet** [SamuelGuillemet/SEAK#39]
Here is a description of a possible roadmap to extend the project:

- [ ] Save `quickfix-server` messages id with Redis
- [ ] Save `order-book` market data subscription to Redis
- [ ] Save `order-book` order-book orders to Redis
- [ ] Add routes to read and modify market data subscriptions
- [ ] Add routes to read and reset order-book orders
- [ ] Add init methods to load default value to the order-book
